In [1]:
import utils as cu
entity_match_request ={
    "input": [{"name":"Apple Inc.","clientId": "abc-123"},
    {"name":"Microsoft Corporation", "clientId": "abc-123"},
    {"name":"Amazon.com, Inc.", "clientId": "abc-123"},
    {"name":"Tesla Inc", "clientId": "abc-123"},
    {"name":"Alphabet Inc. Class A", "clientId": "abc-123"},],
    "includeEntityType": ["PUB"],
    "excludeEntityType": ["EXT"],
    "includeEntitySubType": ["PR"],
    "excludeEntitySubType": ["AR"],
    "includeParent": False
    }

cu.search_symbols(entity_data=entity_match_request)

,taskId,universeId,clientId,clientBbgFigi,clientBbgTicker,clientBic,clientCik,clientCountry,clientCrd,clientCusip,...,locationCity,regionName,factsetIndustryCode,factsetIndustryName,factsetSectorCode,factsetSectorName,parentName,parentMatchFlag,nameMatchString,nameMatchSource
0,None,None,abc-123,None,None,None,None,None,None,None,...,Cupertino,North America,1320,Telecommunications Equipment,1300,Electronic Technology,None,False,apple inc,Proper/ Legal Name
1,None,None,abc-123,None,None,None,None,None,None,None,...,Beijing,Far East,None,None,None,None,None,False,apple,Proper/ Legal Name
2,None,None,abc-123,None,None,None,None,None,None,None,...,Saitama,Far East,None,None,None,None,None,False,apple kk /saitama/,Proper/ Legal Name
3,None,None,abc-123,None,None,None,None,None,None,None,...,None,North America,None,None,None,None,None,False,apple ltd,Proper/ Legal Name
4,None,None,abc-123,None,None,None,None,None,None,None,...,None,Indian Subcontinent/Central Asia,None,None,None,None,None,False,apple corp ltd,Proper/ Legal Name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,None,None,abc-123,None,None,None,None,None,None,None,...,None,Europe,None,None,None,None,Bayerische Motoren Werke AG,False,alphabet,Domain Name
93,None,None,abc-123,None,None,None,None,None,None,None,...,Munich,Europe,3205,Miscellaneous Commercial Services,3200,Commercial Services,Bayerische Motoren Werke AG,False,alphabet,Domain Name
94,None,None,abc-123,None,None,None,None,None,None,None,...,Warsaw,Europe,4830,Finance/Rental/Leasing,4800,Finance,Bayerische Motoren Werke AG,False,alphabet,Domain Name
95,None,None,abc-123,None,None,None,None,None,None,None,...,None,North America,4845,Investment Managers,4800,Finance,"Alphabet, Inc.",False,alphabet inc /ca/,Proper/ Legal Name
96,None,None,abc-123,None,None,None,None,None,None,None,...,None,Europe,None,None,None,None,None,False,alphabetim sas,Proper/ Legal Name

In [7]:
import utils as cu
people_match_request ={
    "input": [{"personName":"Andy Jassy",'entity' :'Amazon'},
               {"personName":'Tim Cook','entity':'Apple'}],
    }

cu.search_people(people_data=people_match_request)

,taskId,activeRole,clientEntity,clientFirstName,clientLastName,clientMiddleName,clientSalutation,clientSuffix,clientPriority,clientPersonName,...,clientId,entity,mapStatus,matchFlag,nameMatchSource,nameMatchString,rowIndex,similarityScore,title,universeId
0,None,true,Amazon,None,None,None,None,None,None,Andy Jassy,...,None,AMAZON COM INC,MAPPED,true,Institutional Affiliation,andrew jassy,0,1.0000,"President, Chief Executive Officer & Director",None
1,None,false,Amazon,None,None,None,None,None,None,Andy Jassy,...,None,HARVARD UNIVERSITY,None,false,Institutional Affiliation,andrew jassy,0,1.0000,None,None
2,None,true,Amazon,None,None,None,None,None,None,Andy Jassy,...,None,RAINIER SCHOLARS,None,false,Institutional Affiliation,andrew jassy,0,1.0000,Trustee,None
3,None,true,Amazon,None,None,None,None,None,None,Andy Jassy,...,None,HARVARD BUSINESS SCHOOL,None,false,Institutional Affiliation,andrew jassy,0,1.0000,None,None
4,None,true,Amazon,None,None,None,None,None,None,Andy Jassy,...,None,RAINIER PREP,None,false,Institutional Affiliation,andrew jassy,0,1.0000,Chairman,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,None,true,Apple,None,None,None,None,None,None,Tim Cook,...,None,URBAN ELEVATOR SERVICE FL,None,false,Institutional Affiliation,timothy cook,1,1.0000,Co-Chief Executive Officer,None
281,None,false,Apple,None,None,None,None,None,None,Tim Cook,...,None,"Athenex, Inc.",None,false,Institutional Affiliation,cook timothy devere,1,1.0000,None,None
282,None,false,Apple,None,None,None,None,None,None,Tim Cook,...,None,Pushpay Holdings Ltd.,None,false,Institutional Affiliation,cook timothy john /pushpay/,1,1.0000,None,None
283,None,true,Apple,None,None,None,None,None,None,Tim Cook,...,None,MERCK SHARP & DOHME CORP,None,false,Institutional Affiliation,tim cooke,1,0.7756,Head-IT & Quality Management,None
284,None,false,Apple,None,None,None,None,None,None,Tim Cook,...,None,Deltic Energy Plc,None,false,Institutional Affiliation,cooke tim /deltic/,1,0.7756,None,None